### PR TITLE
refactor for file receiver service bus

### PR DESCRIPTION
**Pull request by samplackett**

### CODE REVIEW

**Review by GodsonLeigh — APPROVED** [review]
boratapprove

**Review by GodsonLeigh — DISMISSED** [review]
allow-gif

**Comment by samplackett** [comment]
Held until CCoE confirm creation of topic

**Review by kiranpal-atos — APPROVED** [review]
LGTM!

**Review by GodsonLeigh — DISMISSED** [review]
kimkardashian-mhmm

**Review by GodsonLeigh — APPROVED** [review]

**Pull request merged**
